// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface SauceNAOResponse {
	header: SauceNAOResponseHeader
	results: Result[]
}

export interface SauceNAOResponseHeader {
	user_id: string
	account_type: string
	short_limit: string
	long_limit: string
	long_remaining: number
	short_remaining: number
	status: number
	results_requested: string
	index: { [key: string]: Index }
	search_depth: string
	minimum_similarity: number
	query_image_display: string
	query_image: string
	results_returned: number
}

export interface Index {
	status: number
	parent_id: number
	id: number
	results?: number
}

export interface Result {
	header: ResultHeader
	data: Data
}

export interface Data {
	ext_urls: string[]
	title?: string
	da_id?: number
	author_name?: string
	author_url?: string
	gelbooru_id?: number
	creator?: string
	material?: string
	characters?: string
	source?: string
}

export interface ResultHeader {
	similarity: string
	thumbnail: string
	index_id: number
	index_name: string
}
